# Generated by Django 3.2 on 2023-01-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=' ', max_length=150, null=True, verbose_name='Имя'),
        ),
    ]
