# Generated by Django 3.2 on 2023-01-27 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_title_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.MaxValueValidator(limit_value=256, message='Название произведения не может быть длиннее 256 символов.')], verbose_name='Название произведения'),
        ),
    ]
