# Generated by Django 3.2 on 2023-01-27 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_title_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.MaxLengthValidator(limit_value=256, message='Не более 256 символов.')], verbose_name='Название произведения'),
        ),
    ]
